### ISSUE TITLE
implement test vignette for scenario I of our valdation concept

### ISSUE THREAD

**Issue by kkmann** [kkmann/adoptr#101]
This should be the template for all other scenarios. Work out how exactly we are describing everything, the structure and how we handle test cases (where to throw errors). Also need to check how we get this build and deployed on Travis-CI without running into time-limit problems!

**Comment by MatheMax** [comment]
I think this is done by
https://kkmann.github.io/adoptrValidation/articles/scenario-I.html
@kkmann do you agree?
