### ISSUE TITLE
revise one/two-arm strategy

### ISSUE THREAD

**Issue by kkmann** [kkmann/adoptr#112]
how do we document this?

**Comment by kkmann** [comment]
@MatheMax not sure that we actually need to change any code. I think we now have a consistent implementation where any n is always per group (and we either have two groups or one). So this is probably just a documentation issue. If you agree feel free to move the issue back to v0.1.0.

**Comment by MatheMax** [comment]
Yes I'm also happy with the current implementation
Documentation could and will be updated to make it more clear
