### ISSUE TITLE
Gaussian Quadrature for pivots

### ISSUE THREAD

**Issue by MatheMax** [kkmann/adoptr#113]
https://github.com/kkmann/adoptr/blob/d08b46b9f43b55b6b358739889ac063034225094/R/ContinuousPrior.R#L108-L109

Is this still a ToDo?
I am not sure if we need it. 
But if yes, I would propose a slot "pivots" of "ContinuousPrior". Otherwise it would take too much runtime I think

**Comment by kkmann** [comment]
not really, seems to work asis, right?

**Comment by MatheMax** [comment]
Right. Then, I'll delete the ToDo

**Comment by MatheMax** [comment]
c.f. #116
