### ISSUE TITLE
TwoStageDesign constructor

### ISSUE THREAD

**Issue by kkmann** [kkmann/adoptr#123]
I don't like our current approach to constructing TwoStageDesigns. The user shouldn't be bothered with GQ stuff since we exclusively use it now. 

Why not simply have two constructors, one where the pivots are given as vectors (for complete control) and one where they are given by a single number to quickly get an initial design e.g.

    TwoStageDesign(n1, c1f, c1e, 50, 1.96, order = 5L)
    TwoStageDesign(n1, c1f, c1e, rep(50, 5), rep(1.96, 5))

**Comment by MatheMax** [comment]
c.f. #128
