### ISSUE TITLE
Initial Design

### ISSUE THREAD

**Issue by MatheMax** [kkmann/adoptr#147]
We could implement a method propose_initial_design() to make usage even more comfortable

**Comment by kkmann** [comment]
rough idea: start with one-stage (most robust, make the initial size for this problem accessible!), should optimal GS be used as initial for TS?

**Comment by kkmann** [comment]
@MatheMax is this still necessary/feasible? I doubt that there is a robust way to do that - do you still want to follow this up? If not, please close!
