### ISSUE TITLE
conditioning

### ISSUE THREAD

**Issue by kkmann** [kkmann/adoptr#150]
@MatheMax 

why do we need this?

https://github.com/kkmann/adoptr/blob/fa1fb7d50fc93f3d49abe69e64a617543bab0f57/R/ContinuousPrior.R#L73-L78

**Comment by MatheMax** [comment]
helps to obtain a "correct" support if the user is using sth way too large. 
But shouldn't be necessary, so we can also delete it if you want

**Comment by kkmann** [comment]
my rationale is, that - if we do it - the check should be conducted when creating a continuous distribution (in the constructor). Checking again should then not be necessary when conditioning and the behavior is more predictable.

How do you feel about making this optional with default; tighten_support = FALSE and a warning if the support is not tight?

**Comment by MatheMax** [comment]
> 
> 
> my rationale is, that - if we do it - the check should be conducted when creating a continuous distribution (in the constructor). Checking again should then not be necessary when conditioning and the behavior is more predictable.

I see the problem that a ContinuousPrior is created in every iteration when the posterior is computed.
Hence, it would (a) cost runtime and could (b) make the support too small for sensitive results

> 
> How do you feel about making this optional with default; tighten_support = FALSE and a warning if the support is not tight?

c.f. above. do you mean an argument of "condition" or of  the constructor "ContinuousPrior"?

**Comment by kkmann** [comment]
I'd go for 

    ContinuousPrior(pdf, support, tighten_support = FALSE)

and remove it from conditioning since conditioning only increases pdf

**Comment by MatheMax** [comment]
c.f. #154
