### ISSUE TITLE
OneStageDesign conversion

### ISSUE THREAD

**Issue by kkmann** [kkmann/adoptr#165]
@MatheMax the conversion from one-stage to two-stage designs looks a bit fishy to me, shouldn't one need to specify an integration order here? I think you are currently using a defualt of 2...
Can we also get a test case for that?

https://github.com/kkmann/adoptr/blob/04b6c2ce9362ce55269765c9b12fbb16ce349406/R/OneStageDesign.R#L86-L99

**Comment by MatheMax** [comment]
Why do we need this? 
Isn't it unnecessary complicated because it shouldn't be "really" integrated?
The n2-pivots are set to "0" because there is no second stage.

**Comment by kkmann** [comment]
I claim, that's

https://github.com/kkmann/adoptr/blob/f068eefe5dde56110384de63a3726db642cf641f/R/OneStageDesign.R#L88-L103

the way to do it, happy to get your review. Needed to fix the messed up TwoStageDesign() generic along the way...

**Comment by MatheMax** [comment]
can be closed with #167
