### ISSUE TITLE
Conditional constraints and continuation region

### ISSUE THREAD

**Issue by MatheMax** [kkmann/adoptr#170]
I'll delete the following ToDo in the next PR.

https://github.com/kkmann/adoptr/blob/94a0f454543f7ed93ac6958c3deb9e121bedd99a/R/constraints.R#L7-L9

However, we have to think about how to handle this. 
CP and CSS are clearly defined outside the continuation region. Hence, for these both guys it is not necessary to implement anything, or am I wrong?

**Comment by kkmann** [comment]
i guess the idea is to allow the specification of an interval for x1 for which a constraint should hold
