### ISSUE TITLE
make sure ALL exported functions have and @example section

### ISSUE THREAD

**Issue by kkmann** [kkmann/adoptr#173]
CRAN comment:
> Please provide small executable examples in all your Rd files to
illustrate the use of the exported function but also enable automatic
testing.

**Comment by kkmann** [comment]
> Please provide small executable examples in all your Rd files to
illustrate the use of the exported function but also enable automatic
testing.

**Comment by MatheMax** [comment]
I think with #185 all Rd files in man have a \examples part
