### ISSUE TITLE
idea: visual summary on adoptr webpage

### ISSUE THREAD

**Issue by shareCH** [kkmann/adoptr#180]
create a visual summary of the different options and their relations (e.g. specification of design incl. Prior, constraint defintion, solving optimization Problem, etc.)

**Comment by kkmann** [comment]
:+1: like it!

**Comment by kkmann** [comment]
@shareCH I still like the idea a lot - do you still want to follow this up?

**Comment by shareCH** [comment]
Yes, I  sketch something for the article.

**Comment by kkmann** [comment]
:+1:

**Comment by kkmann** [comment]
closing this, still feel it is a good idea but we need a concrete pitch!
