### ISSUE TITLE
Formatting pdf: Index 

### ISSUE THREAD

**Issue by shareCH** [kkmann/adoptr#187]
Index (pdf) needs formatting

**Comment by kkmann** [comment]
@MatheMax talked to Caro. Problem is that we use fairly long class names (which I find necessary!) and the pdf probably uses tttext{} in the index (no line breaking). So, nothing we can do. Luckily most people won't ever look at the pdf manual and even if they do they will probably not look at the index... and even if they do look at the index it is just ugly not unusable ;)
