### ISSUE TITLE
CompositeScore done right

### ISSUE THREAD

**Issue by kkmann** [kkmann/adoptr#188]
So far, we only support affine (conditional) scores - nice, but limited. 
It would be much cooler to support arbitrary expressions of scores - the problem is that we cannot subclass 'numeric' (which would be the OO way of doing this). We can, however, use R's expression magic to do something like:

```
setClass("Score", list(
    value = "numeric"
))

Score <- function(value) new("Score", value = value)

setGeneric("evaluate", function(a, x, ...) standardGeneric("evaluate"))

setMethod("evaluate", signature("Score"), function(a, x, ...) a@value + x)

setClass("CompositeScore", list(
    expr = "{",
    vars = "list"
),
contains = "Score"
)

CompositeScore <- function(expr) {

    vars <- mget(
        all.vars(substitute(expr)),
        parent.frame(n = 1),
        inherits   = FALSE,
        ifnotfound = list(NA)
    )

    res <- new("CompositeScore",
               value = NaN,
               expr  = substitute(expr),
               vars  = vars
    )

    # test vectorization
    tmp <- evaluate(res, -1:1)
    if (!is(tmp, "numeric") | length(tmp) != 3)
        stop("expr must support vectorization for evaluation")

    return(res)

}

setMethod("evaluate", signature("CompositeScore"),
          function(a, x, ...) {

              values = list()
              if (length(a@vars) > 0) {
                  values   <- lapply(
                      a@vars[sapply(a@vars, function(x) is(x, "Score"))],
                      function(a) evaluate(a, x, ...)
                  )
              }

              return(eval(a@expr, values))

          }
)

# example

a <- Score(1)
b <- Score(2)
c <- .5

x <- 0:3

evaluate(a, x) + c*sin(evaluate(b, x))

tmp <- CompositeScore({a + c*sin(b)})
evaluate(tmp, x)

# fancy example

tmp2 <- CompositeScore({
    res <- 0;
    for (i in 1:3) {
        res <- res + a
    }
    res
})
evaluate(tmp2, x)
3*evaluate(a, x)

evaluate(CompositeScore({
    numeric(length(a)) + 1
}), x)

CompositeScore({
    1
})
```

works like a charm ;) Should replace the complete AffineScore machinery...

**Comment by MatheMax** [comment]
Hey @kkmann, is the implementation in #189 as you planned? 
If yes, I'd add docs and tests ;)
Quite nice that it works for conditional and unconditional scores simultanously

**Comment by kkmann** [comment]
@MatheMax just played around with it a bit - wasn't really consistent since you could not for expectations of composite conditional scores. I proposed a mechanism using class dispatch. The entire composition mechanism is just 63 lines of code x) so much easier than what we had before. Do let me know when you have any doubts - we need to test this very well since it is a bit 'hacky'.

**Comment by kkmann** [comment]
#189 is merged; there are still some inconsistencies with respect to our class structure that prevent merging #190.
in a nutshell: it does not make much sense to have prior and data distribution in EACH ConditionalScore; expected() should accept these as arguments instead!

**Comment by kkmann** [comment]
yupp, looks like #190 went in the right direction. Docs / validation need to be updated but tests/vignettes work already
