### ISSUE TITLE
reference paper in vignette / docs / validation 

### ISSUE THREAD

**Issue by kkmann** [kkmann/adoptr#191]
as soon as it is out ;)

**Comment by kkmann** [comment]
need to release 0.2.0 earlier due to broken tests (rpact) pushing this back

**Comment by kkmann** [comment]
@MatheMax please add link to online version of SIM Article to:
[ ] README.Rmd
[ ] Index.Rmd
[ ] Package documentation (landing page)
[ ] Vignette

**Comment by MatheMax** [comment]
cf. #211
