### ISSUE TITLE
test

### ISSUE THREAD

**Issue by kkmann** [kkmann/adoptr#200]
@MatheMax  sorry, what exactly are we testing here?

https://github.com/kkmann/adoptr/blob/603b20eb30b963f2aa45f78398547cf41856ba5a/tests/testthat/test_composite.R#L86-L106

**Comment by MatheMax** [comment]
Test 1: Can integers be predefined and then used in "composite"? (was the problem in the validation report)
Test 2: "linearity" of expected(composite(.))

at least this was the idea of the first one, I think the second was your own implementation ;)

**Comment by kkmann** [comment]
@MatheMax I think we are covering both cases with the test before and the one I added after (even through function calls which is what we need for the example in the Val report) - plz comment/delete

**Comment by MatheMax** [comment]
deleted in #201
