### ISSUE TITLE
rpact updated - breaks our tests

### ISSUE THREAD

**Issue by kkmann** [kkmann/adoptr#204]
chron job fails, it's the rpact dependency, they updated from 1.0.0 to 2.0.0 oO

**Comment by kkmann** [comment]
@MatheMax I think I resolved the issues BUT, there was a lot of nonsensical expect_eqal constructs in the tests. expect_eqal + tolerance does not work as you 'expect' it x(
Could you take care of hunting down the remaining expect_equal problems? have a look at commit 56dec94d8fe20909511de569d7affe8a958c4e2a and the docs for all.equal() for details.

**Comment by MatheMax** [comment]
@kkmann Do I understand correctly that "expect_equal" only produces problems when a "tolerance" is defined?

**Comment by MatheMax** [comment]
I fixed these in #206
