### ISSUE TITLE
Make conditional power computation faster in optimization

### ISSUE THREAD

**Issue by MatheMax** [kkmann/adoptr#215]
https://github.com/kkmann/adoptr/blob/3c1b524d1044bcc4f095115a6621758e53b6bbb0/R/ConditionalPower.R#L63-L74

Here, we can differentiate between optimization yes/no

**Comment by kkmann** [comment]
the idea being, that during optimization the expected value can directly be computed as weighted sum over the pivot points.

**Comment by MatheMax** [comment]
cf. #218
