### ISSUE TITLE
Come up with a better name

### ISSUE THREAD

**Issue by kkmann** [kkmann/adoptr#22]
OTSD is as interesting and memorable as this ... other thing I recently heard about and cannot remember now. 

I am scratching my head but cannot come up with anything better than BAdaSS for Bayesian Adaptive Sample Size - a controversial choice. I am not quite sure whether using 'BAdaSS designs' would be a pro or con in a grant application...

**Comment by kkmann** [comment]
designr? would be easy to come up with a hex-sticker for that ;)

**Comment by MatheMax** [comment]
First idea of MK: AdOpt

**Comment by kkmann** [comment]
not bad! I'd like to avoid adaptive for the reasons we discussed but that applies to badass just as well. viable option, definitely!

**Comment by MatheMax** [comment]
@kkmann , do we used "adpotr"?

**Comment by kkmann** [comment]
totally happy, but that goes last - renaming a package / repo is some fuzz ;)

**Comment by kkmann** [comment]
#86
