### ISSUE TITLE
summary 

### ISSUE THREAD

**Issue by MatheMax** [kkmann/adoptr#226]
Currently, 'summary' just prints the added unconditional scores.

https://github.com/kkmann/adoptr/blob/4e46f5ad4ee66c4ea2297ac1b823443809d2cf5f/R/TwoStageDesign.R#L512-L531

Do we want to extend this?
We may add the first stage parameters and the n2- and c2-pivots.

**Comment by kkmann** [comment]
yeah, that sounds fair. I guess my motivation for taking it out was the slightly awkward formatting of the last implementation. should be very dense (not too high).

A funny idea would be using the txtplot package to print n(x1) and c2(x1), the height is adjustible and its text only.

So we would have whatever summary scores (and n1?) in the first 'row'

then a row(!) with c1f, integration pivots, c1e (no weights, they are irrelevant)

and two txtplots with n2(x1) and c2(x1) ?

**Comment by kkmann** [comment]
like so ;)

```
> txtplot(seq(0, 2*pi, .01), sin(seq(0, 2*pi, .01)), height = 10)
   1 +--+---------+--*****-+---------+--------+---------+--------+-----+
     |         ******    *******                                       |
 0.5 +      ****               ****                                    +
     |   ****                     ****                                 |
   0 +  **                           ***                           **  +
     |                                 ****                     ****   |
-0.5 +                                    ****               ****      +
     |                                       ******     ******         |
  -1 +--+---------+--------+---------+--------+---******+--------+-----+
        0         1        2         3        4         5        6      
```

**Comment by MatheMax** [comment]
Looks nice, but is it worth to depend on an additional package?

**Comment by kkmann** [comment]
good point, it's optional anyway. we can add it at the end of summary or not, prob not worth it since we have plot() ...

**Comment by MatheMax** [comment]
cf. #228 for a proposal

**Comment by kkmann** [comment]
closing this one -> #228
