### ISSUE TITLE
examine alternative optimizers

### ISSUE THREAD

**Issue by kkmann** [kkmann/adoptr#48]
Following #47, it might be worthwhile playing around with other optimizers or at least think about ways to implement that. Stochastic global optimizers might be an option but I am not sure as to how well they handle non-linearly constraint problems.

**Comment by kkmann** [comment]
augmented lagrangian with finite differences gradient?

**Comment by kkmann** [comment]
@MatheMax I think you did some work here - anything of common interest? Things that we can drop / should pursue further?

**Comment by MatheMax** [comment]
I uploaded a version in the branch "optimizer" 
It's the only combination that is at least working but I do not see that we are gaining runtime with this...

**Comment by kkmann** [comment]
thx, let's leave it for the moment.

**Comment by MatheMax** [comment]
I didn't leave it ;)
In the validation package you can see that COBYLA does not converge in case I.2 (ess under null, point prior) even after 50,000 iterations. Trying the same with the optimizer-branch takes around 200 iterations and converges much faster

**Comment by kkmann** [comment]
x) so, how does augmented lagrangian perform in the other cases?

**Comment by kkmann** [comment]
any chance of having both variants as options? augmented lagrangian just requires the additional definition of a derivative, right?

**Comment by kkmann** [comment]
Okay, had a look at your suggestion in more detail @MatheMax , you are not using augmented Lagrangian but SLSQP, I have zero experience with that. Since it is a second-order method, it should converge fairly quickly. Implementation is straight forward (although I'd prefer not to depend on numDeriv since it seems to be fairly stale atm). 

Look's like we have a few options: 

* COBYLA seems to work but sometimes exhibits strange convergence behavior ('artifacts' in n/c function if stopped prematurely)

* augmented Lagrangian is a very general concept with different choices of local optimizers, not yet tested.

* sequential least squares seem to work as well, maybe better convergence properties - what about precision/smoothness of the final designs; runtime? 

* things might also get better by scaling the inputs: currently n and c are on very different scales (100s vs 0-3) this may affect speed/precision negatively and could be solved by e.g. scaling n appropriately.
similarly, this scaling issue might affect the performance of finite differences methods.

* it is pretty straight forward to play around with optimizers since it only affects minimize/postprocess internally

I'd still be in favor of finding out which methods works best across the entire range of designs. Best necessarily trading off between precision/speed/stability/simplicity.

Do you think it is feasible to give this some more time and postpone v0.1-beta? We should agree on a metric for comparing optimizer performance across all problems before digging deeper into this...

**Comment by MatheMax** [comment]
I removed the milestone but I think we can leave this opened and keep it in mind when we talk to s.o. who could help us with this topic

**Comment by kkmann** [comment]
I think we pretty much settled on COBYLA for R, closing this but feel free to reopen if something comes along...
