### ISSUE TITLE
implement more examples to check plausibility

### ISSUE THREAD

**Issue by kkmann** [kkmann/adoptr#50]
We need (all with toer on boundary of null hypothesis):

- [ ] point alternative:
    - [ ] large value (0.4)
        - [ ] ESS under null
        - [x] ESS under 0.4
    - [ ] small value (0.2)
        - [ ] ESS under null
        - [ ] ESS under 0.2
- [ ] continuous normal prior
    - [ ] ESS under null
    - [ ] ESS under normal prior
- [ ] uniform prior on small interval ([.3, .5]?)
    - [ ] ESS under null
    - [ ] ESS under normal prior
- [ ] all of the above with expected power using the alternative 
- [ ] all of the above (only expected power) with constraint on conditional power 

Those should all eventually end up as test cases (ideally these would not be copy paste but 
programmatically generated from matrix of hypotheses / conditions).

Constraints and final ESS should be checked usig simulate().

I would star, however, by picking 4-8 most important examples and implement them in a vignette. This vignette 'examples' automatically ends up in the online documentation (pkgdown).
Once we are happy with the results, these can be 'frozen' by using test_known_value again...

**Comment by MatheMax** [comment]
Hey @kkmann 
what do you mean with expected power here?
Don't we always use expected power when we calculate the power or do I missunderstand something?

**Comment by kkmann** [comment]
terminology... technically we do but for a point mass prior with mass 1 on a single delta it isn't really an expectation, right?

**Comment by MatheMax** [comment]
so you mean to minimize ess under a point alternative by requierung the expected power >= 1 - beta, right?

**Comment by kkmann** [comment]
this is kind of interlinked with #16. I'll try to structure my high-level thoughts on this. Aims:

1. test that our optimization works as expected in the sense of unit testing / testthat. The rationale here is just to check that we do not have any stupid bugs in the code. The objectives of these tests should not be to assure that we get valid/correct designs but that the optimization function returns the expected output. Since these will be run regularly, they must be pretty quick. Ideally, we would only optimize one or two designs, just enough to get our coverage to  100%. Maybe even working with strong regularization / few pivots (5).

2. test correctness of the resulting designs. this is much harder and what I meant with #16. I would split this in two sub-tasks:
    1. Internal plausibility check: use simulate to check properties of optimized desings (power expected sample size / conditional power etc.). Also, does the shape of a desing change as expected when varying the alternative (delta  = .2, delta = .4, delta = N(.3, .2) or something like that). TSD > GSD > OSD?
    2. external validation against results from other packages / sas (again, only for a subsample, where possible)

Structurally, 1. goes in the package itself. 2., however, might run for hours/days if done properly. This should be done in a separate 'validation' package. I'll try to set up the infrastructure for that. There are a few design choices and I did not quite make up my mind as to how to do this. a) implement everything as test. Very formal but limited in terms of output (validation report). b) as vignettes. Less formal but would provide a set of validation reports (=vignettes). Here, the challange lies in the automatic testing. you would probably have to import testthat and manually invoke test_that() in the vignette. seems doable and the easiest way of achieving automated testing + report. We then need to configure the build system such that is compiles the entire vignette, even if we encounter errors, print these errors in the report and let the travis script fail if we encountered an error. We'd then run the build script either by hooking it up to the otsd repository to listent to pushes to master and/or on a weekly basis. the build status of the validation package can then be linked (as badge) back to the actual package.

**Comment by kkmann** [comment]
validation suite is set up https://github.com/kkmann/adoptrValidation.
results for nloptr seem to differ between local and travis build....

**Comment by kkmann** [comment]
newest build is automatically hosted to https://kkmann.github.io/adoptrValidation/

**Comment by kkmann** [comment]
@MatheMax could you give an update (here or link to issue at adoptrValidation) on the structure/scope of the validation tests you intend to implement? I think it would be nice to agree on a concrete structure that we can just tick off one by one.

**Comment by MatheMax** [comment]
*[] test

**Comment by kkmann** [comment]
what is that supposed to mean?

>     Large effect size (delta = 0.4) with normal prior

N(.4, .2) or similar?

Which designs do you check externally (and how)
Which designs do you check internally vs. GS and single stage?
I guess you will always check toer control using simulation and power where applicable?
What about checking the reported expected sample size/objective via simulation in some cases?
What about assessing 'convergence' for making a prior gradually sharper?

**Comment by MatheMax** [comment]
> 
> 
> what is that supposed to mean?
> 
> > ```
> > Large effect size (delta = 0.4) with normal prior
> > ```
> 
> N(.4, .2) or similar?
Yes

> Which designs do you check externally (and how)
All without conditional power constraint

> Which designs do you check internally vs. GS and single stage?
GS: all
single stage: all without conditional power constraint

> I guess you will always check toer control using simulation and power where applicable?
yes

> What about checking the reported expected sample size/objective via simulation in some cases?
I can add this

> What about assessing 'convergence' for making a prior gradually sharper?
@kkmann could you please specify?

**Comment by kkmann** [comment]
> > Which designs do you check externally (and how)
> 
> All without conditional power constraint
> 

cool! Though, probably not those with Bayesian prior, right?

> > Which designs do you check internally vs. GS and single stage?
> 
> GS: all
> single stage: all without conditional power constraint

also cool, but feel free to do that only on a subset - I fear that this wil run for ages if we do the full grid of all possibilites ;) 

> > I guess you will always check toer control using simulation and power where applicable?
> 
> yes

top, I feel this really should be done everywhere - doesn't take much time anyway.

> > What about checking the reported expected sample size/objective via simulation in some cases?
> 
> I can add this

Not really necessariy for all though, right?

> > What about assessing 'convergence' for making a prior gradually sharper?
> 
> @kkmann could you please specify?

sorry - I'd expect some kind of convergende towards the point-prior design if we use e.g. an increasingly narrow uniform prior around the point mass.
Should look at this and then formulate the expectation ;)

**Comment by kkmann** [comment]
Generally speaking I feel doing everyting for all situations might a) be boring b) inflates the validation report to a point where it is hard to take in c) will take ages.
This is exactly why I'd propose to expand your list by adding the details about what exactly you want to do in each situation (what situation is looked at, which expectations are formally tested). We can then just tick off whatever is already done and I'd suggest adding this 'validation concept' + rationale to the readme of adoptrValidation as a kind of table of contents/overview.

**Comment by kkmann** [comment]
we should probably move discussion to adoptrValidation. 

I transferred you suggestions to the README https://github.com/kkmann/adoptrValidation/blob/master/README.md. Note that you can edit files directly in the browser! I'd suggest we first finish the detailed concept before implementing it - potentially saves a lot of work ;)

**Comment by kkmann** [comment]
split to #100 #101 #102 for better overview
