### ISSUE TITLE
Regularize n1

### ISSUE THREAD

**Issue by kkmann** [kkmann/adoptr#55]
with the new AverageN2 regularizer, we do not penalize n1 at all. I am not saying that this is necessary, but maybe one would like to apply the same amount of regularization to n2 and n1 to avoid changing the shape of a design too much. This can be easily done by adding a regularizer just penalizing n1. Non, critical, I am not assigning a milestone but we might want to keep this in the backlog.

**Comment by MatheMax** [comment]
see PR #79 for this issue

**Comment by kkmann** [comment]
we should make the naming more consistent and then it looks good to go! Maybe we need to tweak the documentation a bit

**Comment by kkmann** [comment]
#79
