### ISSUE TITLE
determine final suggested integration order

### ISSUE THREAD

**Issue by kkmann** [kkmann/adoptr#56]
We should come up with a final suggest default for the order of integration.

Criteria are 'nicety' of the resulting n2/c2 functions (smooth enough?) and run time since I suspect that our crappy optimizer will converge a lot faster with fewer parameters.

Goes hand-in-hand with the default relative tolerance and maximum number of iterations.

This is not a priority, correctness and feature completeness are more important but it should be investigated systematically.

**Comment by kkmann** [comment]
I fear everything below 9 is a bit coarse. Maybe we can get better by using a different extrapolation method for n2 and c2?

**Comment by kkmann** [comment]
@MatheMax new thought - we currently do linear interpolation on the n2 pivots - why? We could try to get a cubic spline interpolation to get a smoother curve. In that case, 5 pivots might actually be enough! Trivial to change, you should check it out! Only risk is that the splines get unstable and overshoot but i doubt it...

**Comment by kkmann** [comment]
I suggest doing this based on #101. Should be sufficient to preliminarily decide this. Should anything come up during #102 we can still revise our decision.

**Comment by kkmann** [comment]
hm, just had another look at a result from order 7 + linear interpolation - it feel cubic might be better (maybe with even just 5 pivots)

**Comment by kkmann** [comment]
I guess cubic + 5 should be the default (just need to make sure that n/n2>=1 and c2>=0). It might help with constraint violations (simulate) when we increase the number of pivots, but not quite sure. 
The general recommendation would then be to start with 5 for qualitatively selecting a design and once a particular one is picked to rerun it with more pivots (if we find that that actually helps).

**Comment by MatheMax** [comment]
The results from scenario I confirm your thoughts
5 leads to nice results when enough iterations are made
Do you agree to determine this @kkmann ?

**Comment by kkmann** [comment]
I am happy to stick with 5 if 6/7 takes too long and does not give us significant improvement in terms of constraint compliance

**Comment by kkmann** [comment]
since the optimizer will stick with cobyla atm - I think we can close this, right? we will need a scenario/cases in the validation package to assess impact of increasing the number if pivots though.

**Comment by MatheMax** [comment]
Yes, it can be closed.
The scenario you describe is already implemented and built right now.
I think it should be online in less than one hour.
