### ISSUE TITLE
check for duplicate scores

### ISSUE THREAD

**Issue by MatheMax** [kkmann/adoptr#63]
We have to fix the ToDo in AffineScoreFunction regarding duplicated scores. 

https://github.com/kkmann/otsd/blob/7b9218b85f325a0bd84cec83d6de01c6aa2a48e1/R/AffineScoreFunction.R#L77

**Comment by kkmann** [comment]
do we need that for 0.1? I'd push it to 0.2, would be awkward for ppl trying to break that ;)

**Comment by kkmann** [comment]
switching to #188 should make this unneccessary
