### ISSUE TITLE
proper status information in minimize()

### ISSUE THREAD

**Issue by kkmann** [kkmann/adoptr#73]
we need to make sure that we return the entire information from the optimization call

https://github.com/kkmann/otsd/blob/7dc292730e9c1ced854c150c8a8ba67428f80002/R/minimize.R#L104

not just the optimal desing

**Comment by MatheMax** [comment]
c.f. #94

**Comment by kkmann** [comment]
#94 merged

**Comment by kkmann** [comment]
hm, sorry for reopening this, but this is still not convincing me!

https://github.com/kkmann/adoptr/blob/05d47798cf6f6363c2c085a3208c669092878212/R/minimize.R#L70-L72

I want a solution where a) all possible nloptr status codes are properly handled b) the original nloptr messages are used for the warning (they are stored in the nloptr return object).
I mean, what the heck is sb supposed to do after being informed that 'The algorithm probably did not converge' ??? ;)

@MatheMax should be done asap, talking about this way too long - you or me?

**Comment by kkmann** [comment]
done as of #98
