### ISSUE TITLE
plot n() properly

### ISSUE THREAD

**Issue by kkmann** [kkmann/adoptr#74]
the `n()` function should be plotted as non-continuous on the stopping boundaries, cf.

https://github.com/kkmann/otsd/blob/7dc292730e9c1ced854c150c8a8ba67428f80002/R/TwoStageDesign.R#L281-L303

**Comment by MatheMax** [comment]
see pr #84

**Comment by kkmann** [comment]
#84

**Comment by kkmann** [comment]
hm, we have the same issue when calling plot() with additional conditional scores - should also be discontinuous at the early stopping boundaries, right?
cf. https://kkmann.github.io/adoptr/articles/adoptr.html, plots of optimized design.

**Comment by MatheMax** [comment]
Yes you're right
Would look better, I'll fix this

**Comment by MatheMax** [comment]
was done in #79 because the check() routine complained about missing "graphics::" 
so, I had to add it anyway

**Comment by kkmann** [comment]
@MatheMax should be fixed as of #55 right?

**Comment by MatheMax** [comment]
done with #79
