### ISSUE TITLE
review documentation

### ISSUE THREAD

**Issue by kkmann** [kkmann/adoptr#87]
We need to review the entire documentation - see where it can be simplified etc.

**Comment by kkmann** [comment]
- [ ] review the entire thing ourselves, clarify, simplify, reference or at least mark todos
- [ ] get sb not involved in the package development to try to understand our package from the docs alone
- [ ] hunt down typos

**Comment by kkmann** [comment]
we should make sure that we use roxygen templates to the maximum possible extent

**Comment by MatheMax** [comment]
https://github.com/kkmann/adoptr/blob/cb7d004e6beeef5abe33acdf5a4aca333c51265e/R/ContinuousPrior.R#L105

@kkmann can we remove this ToDo?

**Comment by kkmann** [comment]
agreed, also see my new suggested structure in #159

**Comment by kkmann** [comment]
thx @MatheMax @shareCH!
