### ISSUE TITLE
test evaluate ~= .evaluate for some scores

### ISSUE THREAD

**Issue by kkmann** [kkmann/adoptr#90]
I think we are currently lacking tests to ensure that the internal version and the version used during optimization return roughly the same values, right?

**Comment by MatheMax** [comment]
Completely right, I'll do this

**Comment by MatheMax** [comment]
https://github.com/kkmann/adoptr/blob/d08b46b9f43b55b6b358739889ac063034225094/tests/testthat/test_IntegralScores.R#L79-L91

Here and in the following lines we are actually doing this for ess, power and toer. Do we need more tests?

**Comment by kkmann** [comment]
oh cool, kinda missed that - thx!
