### ISSUE TITLE
show() methods for our custom classes

### ISSUE THREAD

**Issue by kkmann** [kkmann/adoptr#91]
We need to implement a reasonable show() method for all custom classes. Otherwise, the confusing default list-like method is used. In almost all cases, I'd just print the class name since more detailed output will be too complex/confusing on the terminal, @MatheMax what's your take on this?

**Comment by MatheMax** [comment]
Why don't you like the current implementation?
For instance, when we define power in the usual way, the show()-method returns the class of the prior, its support etc
This could be interesting for some users
And most of the users won't use a show() method as long as it is not part of the package implementation

**Comment by kkmann** [comment]
Hm, some of the objects are just too complex to use the default show() . E.g., TwoStageDesigns - the pivots are not directly helpful for everybody ;) 
I'd also be happy with a custom show methods properly addressing this, but in the interest of time, I'd go with the simpler variant...

**Comment by kkmann** [comment]
>  And most of the users won't use a show() method as long as it is not part of the package implementation

show() is used internally when you call an object directly. I.e. it defines the way stuff is represented in the command line

**Comment by MatheMax** [comment]
Okay I think I see your point.
So, your suggestion would be that show(pow) returns "IntegralScore"?

**Comment by kkmann** [comment]
is the easiest - albeit most non-informative - way, right?

**Comment by MatheMax** [comment]
right ;)

**Comment by MatheMax** [comment]
c.f. #149

**Comment by kkmann** [comment]
I think we are still missing a few constraints objects

**Comment by kkmann** [comment]
lol didnt have latest master locally
